baseURL: "https://brettinternet.com/hugo-slides/"
title: "Slides"
description: "A simple directory for your Reveal.js slides"

params:
  author:
    name: "@brettinternet"
    homepage: "https://brettinternet.com"
  highlightjs:
    theme: "solarized-dark"
  revealjs:
    hash: true
    theme: "solarized"
    pdfMaxPagesPerSlide: 1
