baseURL = "http://brettinternet.com/hugo-slides/"
languageCode = "en-us"
license = "MIT"
name = "Hugo Slides"
tags = []
features = []

[taxonomies]
  tag = "tags"

[author]
  name = "@brettinternet"
  homepage = "https://brettinternet.com"