baseURL: "https://brettinternet.com/hugo-slides/"
title: "Slides"
description: "A simple directory for your Reveal.js slides"
theme: "."
themesDir: "../" # only for this example site

params:
  repo: "https://github.com/brettinternet/hugo-slides"
  author:
    name: "@brettinternet"
    homepage: "https://brettinternet.com"
  highlightjs:
    theme: "solarized-dark"
  revealjs:
    hash: true
    theme: "solarized"
  firebase:
    api_key: "AIzaSyCjcz40PXVc8aNX4f7eTv_S5Y3r7xPNJzY"
    auth_domain: "hugo-slides.firebaseapp.com"
    database_url: "https://hugo-slides.firebaseio.com"
    project_id: "hugo-slides"
    sotrage_bucket: "hugo-slides.appspot.com"
    messaging_sender_id: "675344717926"
    app_id: "1:675344717926:web:dd652868ced0547b9ff5a7"
  presenter_uids: ["DEMO"]
