baseURL: "https://brettinternet.com/hugo-slides/"
title: "Slides"
description: "A simple directory for your Reveal.js slides"
theme: "."
themesDir: "../" # only for this example site

params:
  repo: "https://github.com/brettinternet/hugo-slides"
  author:
    name: "@brettinternet"
    homepage: "https://brettinternet.com"
  highlightjs:
    theme: "solarized-dark"
  revealjs:
    hash: true
    theme: "solarized"
